[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
terminal-tombcrawler = { path = ".." }

argh = "0.1.10"
ariadne = "0.1.5"
crossterm = "0.25.0"
eyre = "0.6.8"
aglet = "0.5.0"
