[package]
name = "terminal-tombcrawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["tui"]

[dependencies]
aglet = "0.5.1"
ahash = "0.8.2"
nom = "7.1.3"
